### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by gcemaj** [kanika127/HPS-ambulance-pickup-architecture#1]
Why is the output format not the path for each ambulance assuming they all start at some hospital at time 0

```
H1 P1 P2 H3 P5 P3 H8 P89
H1 P11 P52 H3 P53 P3 H8 P89
.
.
.
H6 P13 P23 H8 P88 P43 H73
```

**Comment by kanika127** [comment]
The ambulance might start at time 0, but after rescuing some people, it may end up at another hospital from where it could start a new path at a later time.

**Comment by gcemaj** [comment]
> The ambulance might start at time 0, but after rescuing some people, it may end up at another hospital from where it could start a new path at a later time.

When would an ambulance sit idle?

**Comment by kanika127** [comment]
Ideally it wouldn't, but it theoretically could. We are just keeping track of ambulances in this manner.
