### ISSUE TITLE
Validator Problems

### ISSUE THREAD

**Issue by TestSubjector** [kanika127/HPS-ambulance-pickup-architecture#2]
I may have missed something obvious, but while running the validator I encounter the following issue

```shell
23 H2 P43 P229 P25 P115 H2
 Rescued: P43:(69,291,104) and P229:(71,291,163) and P25:(72,289,82) and P115:(74,291,121) at 50 minutes | Ended at Hospital H2:(69,295)

39 H4 P49 P276 P235 P2 H4
 Rescued: P49:(96,42,167) and P276:(100,41,127) and P235:(101,40,132) and P2:(105,45,110) at 90 minutes | Ended at Hospital H4:(96,33)

41 H5 P183 P98 P48 P7 H5
 Rescued: P183:(41,205,97) and P98:(41,208,88) and P48:(29,208,141) and P7:(29,203,103) at 86 minutes | Ended at Hospital H5:(42,201)

47 H3 P60 H3
 Rescued: P60:(37,78,80) at 79 minutes | Ended at Hospital H3:(41,67)

50 H2 P246 P275 P163 P185 H2
 !!! No ambulance left at hospital H2:(69,295) at the start time 50 minutes.
```

From line 1, we can see that an ambulance goes from H2 at 23 minutes and returns back to H2 at 50 minutes.
However, when I try to use this same ambulance at 50 minutes (2nd last line), I'm given the no ambulance at hospital error.
Let me know if any other information is required from my side to debug this issue.

**Comment by kanika127** [comment]
Can you try again? I have fixed a bug. This should be working fine now.

**Comment by TestSubjector** [comment]
Yeah, the output is correct now. Thank you for the fix!
I'll close the issue.
